---
- hosts: all
  become: yes
  vars_files:
    - vars/main.yml
  vars:

    user_name: "{{lookup('env','USER')}}"

    wp_version: 4.0
    wp_install_dir: "{{wp['root_dir']}}"
    wp_db_name: "{{wp['db']}}"
    wp_db_user: "{{wp['user']}}"
    wp_db_password: "{{wp['pw']}}"
    wp_db_host: localhost

    nginx_vhosts: []  # TODO

    mysql_root_password: "{{mysql_root_pass}}"
    mysql_databases:
      - name: "{{wp['db']}}"
      - name: "{{unify['db']}}"
    mysql_users:
      - name: "{{wp['user']}}"
        host: "%"
        password: "{{wp['pw']}}"
        priv: "{{ wp['db'] + '.*:ALL'}}"
      - name: "{{unify['user']}}"
        host: "%"
        password: "{{unify['pw']}}"
        priv: "{{ unify['db'] + '.*:ALL'}}"

    # rbenv:
    #   env: user
    #   default_ruby: "{{ruby['version']}}"
    #   rubies:
    #   - version: "{{ruby['version']}}"
    #     env:
    #       RUBY_CONFIGURE_OPTS: "--enable-shared"
    rbenv:
      env: user
      version: v0.4.0
      default_ruby: "{{ruby.ruby_version}}"
      rubies:
      - version: "{{ruby.ruby_version}}"
        env:
          RUBY_CONFIGURE_OPTS: "--enable-shared"

  roles:
    # - role: geerlingguy.nginx
    # - role: geerlingguy.mysql
    # - role: zzet.rbenv
    #   rbenv_users:
    #     - "{{lookup('env','USER')}}"
    # - role: darthwade.wordpress # I take forever!

  tasks:
    # - include: "tasks/php.yml"
    # - include: "tasks/config_nginx.yml"
    # - include: "tasks/wp_config.yml"
    - include: "tasks/ruby.yml"

  handlers:
    - name: "copy php.ini"
      copy:
        src: "files/fpm-php.ini"
        dest: "/etc/php/7.0/fpm/php.ini"
        mode: 644
        owner: root
        group: root

    - name: restart php
      service:
        name: php7.0-fpm
        state: restarted

    - name: ensure nginx config file is ok
      command: nginx -t

    - name: restart nginx
      command: systemctl reload nginx

    - name: rbenv rehash
      shell: rbenv rehash
