---
- hosts: all
  become: yes
  vars:
    wp_version: 4.0
    wp_install_dir: /var/sites/awesome_wordpress_site
    wp_db_name: wp_db
    wp_db_user: wp_user
    wp_db_password: wp_pw
    wp_db_host: localhost

    nginx_vhosts: []

  roles:
  # - darthwade.wordpress
  # - geerlingguy.nginx

  # tasks:
  # - name: install mysql
  #   action: apt name=mysql state=installed update_cache=yes
