---
- hosts: all
  become: yes
  vars_files:
    - vars/main.yml
  vars:

    user_name: "{{lookup('env','USER')}}"

    wp_version: 4.0
    wp_install_dir: "{{wp['root_dir']}}"
    wp_db_name: "{{wp['db']}}"
    wp_db_user: "{{wp['user']}}"
    wp_db_password: "{{wp['pw']}}"
    wp_db_host: localhost

    nginx_vhosts: []  # TODO

    mysql_root_password: "{{mysql_root_pass}}"
    mysql_databases:
      - name: "{{wp['db']}}"
      - name: "{{unify['db']}}"
    mysql_users:
      - name: "{{wp['user']}}"
        host: "%"
        password: "{{wp['pw']}}"
        priv: "{{ wp['db'] + '.*:ALL'}}"
      - name: "{{unify['user']}}"
        host: "%"
        password: "{{unify['pw']}}"
        priv: "{{ unify['db'] + '.*:ALL'}}"

  roles:
    # - role: geerlingguy.nginx
    # - role: geerlingguy.mysql
    # - role: darthwade.wordpress
    # - role: rvm_io.ruby
    #   tags: ruby
    #   rvm1_rubies:
    #     - 'ruby-{{ruby.ruby_version}}'
    #   rvm1_user: "{{user_name}}"

  tasks:
    # - include: "tasks/php.yml"
    # - include: "tasks/ruby.yml"
    # - include: "tasks/passenger.yml"
    - include: "tasks/config_nginx.yml"
    # - include: "tasks/wp_config.yml"
    - include: "tasks/rails_app_setup.yml"

  handlers:
    - name: "copy php.ini"
      copy:
        src: "files/fpm-php.ini"
        dest: "/etc/php/7.0/fpm/php.ini"
        mode: 644
        owner: root
        group: root

    - name: restart php
      service:
        name: php7.0-fpm
        state: restarted

    - name: test nginx config file
      command: nginx -t

    - name: restart nginx
      command: systemctl reload nginx
