---

- name: Install php packages
  apt:
    name: "{{item}}"
    state: installed
    update_cache: yes

  with_items:
    - php-fpm
    - php-mysql
    - php-curl
    - php-gd
    - php-mbstring
    - php-mcrypt
    - php-xml
    - php-xmlrpc

  notify:
    - restart php

- name: "copy php.ini"
  copy:
    src: "files/fpm-php.ini"
    dest: "/etc/php/7.0/fpm/php.ini"
    mode: 644
    owner: root
    group: root
