---
- name: install php-fpm
  apt: name=php-fpm state=installed update_cache=yes

- name: install php-mysql
  apt: name=php-mysql state=installed update_cache=yes

- name: "fix /etc/php/7.0/fpm/php.ini"
  copy: src=files/fpm-php.ini dest=/etc/php/7.0/fpm/php.ini mode=644 owner=root group=root

- name: restart php
  systemd: name=php7.0-fpm state=restarted
