---
  - name: Ensure git is installed
    apt:
      name: git
      state: installed
      update_cache: yes

  - name: Ensure base and shared dir is created
    file:
      path: "{{item}}"
      owner: "{{user_name}}"
      group: www-data
      recurse: yes
      state: directory
    with_items:
      - "/home/{{user_name}}/unify"
      - "/home/{{user_name}}/unify/shared"
      - "/home/{{user_name}}/unify/shared/config"

  - name: Ensure app variables are in place
    template:
      src: "./templates/rails_application.yml.j2"
      dest: "/home/{{user_name}}/unify/shared/config/application.yml"
    notify:
      - restart nginx
