---
- hosts: all
  become: yes
  vars_files:
    - vars/main.yml
  vars:
    wp_version: 4.0
    wp_install_dir: /var/sites/awesome_wordpress_site
    wp_db_name: "{{mysql['wp']['db']}}"
    wp_db_user: "{{mysql['wp']['user']}}"
    wp_db_password: "{{mysql['wp']['pw']}}"
    wp_db_host: localhost

    nginx_vhosts: []

    mysql_root_password: "{{mysql['rootpass']}}"
    mysql_databases:
      - name: "{{mysql['wp']['db']}}"
      - name: "{{mysql['unify']['db']}}"
    mysql_users:
      - name: "{{mysql['wp']['user']}}"
        host: "%"
        password: "{{mysql['wp']['pw']}}"
        priv: "{{ mysql['wp']['db'] + '.*:ALL'}}"
      - name: "{{mysql['unify']['user']}}"
        host: "%"
        password: "{{mysql['unify']['pw']}}"
        priv: "{{ mysql['unify']['db'] + '.*:ALL'}}"

  roles:
  - darthwade.wordpress
  - geerlingguy.nginx
  - geerlingguy.mysql

  # tasks:
  # - name: install mysql
  #   action: apt name=mysql state=installed update_cache=yes
