# source: https://sysadmincasts.com/episodes/45-learning-ansible-with-vagrant-part-2-4
---
- hosts: all
  sudo: yes
  gather_facts: no
  remote_user: vagrant
  # TODO generalize remote user name to vars. use above and below

  tasks:

  - name: install ssh key
    authorized_key: user=vagrant
                    key="{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
                    state=present
